baseurl      = "https://ssulei7.github.io"
title        = "Sully Squared Blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
publishDir = "docs"

[pagination]
  pagerSize = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "DevOps / Software Engineer, Automation Junkie 🤖"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Sully Suleiman's Blog"
  keys = "sully suleiman, blog, devops engineer, sully squared, suleiman, software engineer, developer, palestinian"
  images = [""]
  giscus = true


[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Sully Squared"
    subtitle = "A blog maintained by Sully Suleiman"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd home"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "post"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "tags"
    name       = "Tags"
    url        = "/tags"

[[params.social]]
    name = "github"
    url = "https://github.com/ssulei7"

[[params.social]]
    name = "hackerrank"
    url = "https://hackerrank.com/sullysquared"